
name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read       # 读取仓库文件
  pages: write         # 发布到 GitHub Pages
  id-token: write      # 支持 OIDC 部署

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-sha: ${{ steps.upload-pages.outputs.artifact-sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build the site
        run: mkdocs build --strict

      - name: Upload Pages artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact-sha: ${{ needs.build.outputs.artifact-sha }}
