name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write       # 允许写入 Pages
  id-token: write    # 支持 OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-sha: ${{ steps.upload.outputs.artifact-sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install mkdocs-material

      - name: Build site
        run: mkdocs build --strict

      - name: Upload Pages artifact
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
        with:
          artifact-sha: ${{ needs.build.outputs.artifact-sha }}